apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: awesome-media-backend-deployment
  namespace: ${parameters.namespace}
  labels:
    app: awesome-media-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awesome-media-backend
  template:
    metadata:
      labels:
        app: awesome-media-backend
        version: v2
    spec:
      containers:
      - name: awesome-media-backend
        image: dtlabs/awesome-media-backend:2.0
        ports:
        - containerPort: 8090
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
            cpu: 50m
          limits:
            memory: 1Gi
            cpu: 500m
